spring.application.name=system-a
spring.datasource.url=jdbc:postgresql://${SYSTEM_A_POSTGRES_HOST:localhost}:${SYSTEM_A_POSTGRES_PORT:5432}/${SYSTEM_A_POSTGRES_DB:system_a_transfer}
spring.datasource.username=${SYSTEM_A_POSTGRES_USER:system_a_user}
spring.datasource.password=${SYSTEM_A_POSTGRES_PASSWORD:system_a_pass_local}
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master-aa.yaml

system-a.zone=Asia/Ho_Chi_Minh
system-a.main-window-cron=0 0,30 9,10 * * *
system-a.final-batch-cron=0 0 11 * * *
system-a.response-poll-start-cron=0 0 9 * * *
system-a.response-poll-main-cron=30 * 9-11 * * *
system-a.response-poll-end-cron=30 0-30 12 * * *
system-a.batch-size=1
system-a.staging-directory=build/generated/outbound
system-a.response-directory=build/generated/response
system-a.sftp-host=${SYSTEM_A_SFTP_HOST:localhost}
system-a.sftp-port=${SYSTEM_A_SFTP_PORT:2022}
system-a.sftp-username=${SYSTEM_A_SFTP_USERNAME:system-a}
system-a.sftp-private-key-path=${SYSTEM_A_SFTP_PRIVATE_KEY_PATH:../infra/generated/keys/system-a-sftp.key}
system-a.sftp-private-key-passphrase=${SYSTEM_A_SFTP_PRIVATE_KEY_PASSPHRASE:}
system-a.remote-send-directory=${SYSTEM_A_REMOTE_SEND_DIRECTORY:/send}
system-a.remote-recv-directory=${SYSTEM_A_REMOTE_RECV_DIRECTORY:/recv}
system-a.remote-ack-directory=${SYSTEM_A_REMOTE_ACK_DIRECTORY:/ack}
system-a.pgp-passphrase=${SYSTEM_A_PGP_PASSPHRASE:LocalPgpPassphrase123!}
