spring.application.name=system-b
server.port=8081

spring.datasource.url=jdbc:postgresql://${SYSTEM_B_POSTGRES_HOST:localhost}:${SYSTEM_B_POSTGRES_PORT:5432}/${SYSTEM_B_POSTGRES_DB:system_b_transfer}
spring.datasource.username=${SYSTEM_B_POSTGRES_USER:system_b_user}
spring.datasource.password=${SYSTEM_B_POSTGRES_PASSWORD:system_b_pass_local}
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master-bb.yaml

system-b.zone=Asia/Ho_Chi_Minh
system-b.poll-start-cron=0 59 8 * * *
system-b.poll-main-cron=0 * 9,10 * * *
system-b.poll-end-cron=0 0-15 11 * * *
system-b.processing-cron=20 * * * * *
system-b.staging-directory=build/generated/inbound/staging
system-b.receipt-directory=build/generated/inbound/receipts
system-b.sftp-host=${SYSTEM_B_SFTP_HOST:localhost}
system-b.sftp-port=${SYSTEM_B_SFTP_PORT:2022}
system-b.sftp-username=${SYSTEM_B_SFTP_USERNAME:system-b}
system-b.sftp-password=${SYSTEM_B_SFTP_PASSWORD:SystemB123!}
system-b.remote-recv-directory=${SYSTEM_B_REMOTE_RECV_DIRECTORY:/recv}
system-b.remote-ack-directory=${SYSTEM_B_REMOTE_ACK_DIRECTORY:/ack}
system-b.remote-send-directory=${SYSTEM_B_REMOTE_SEND_DIRECTORY:/send}
system-b.pgp-passphrase=${SYSTEM_B_PGP_PASSPHRASE:LocalPgpPassphrase123!}
